sudo: required

notifications:
  - email: false

services:
  - docker

install:
  - rm -r -f -d $HOME/.cache/yarn
  - rm -r -f -d node_modules
  - rm -r -f -d ./frontend/node_modules
  - yarn cache clean
  - ./gradlew bootJar

script:
  - ./gradlew integrationTest
