sudo: required

cache: npm

notifications:
  - email: false

services:
  - docker

stages:
  - name: deploy
    if: branch = master

install:
  - cd frontend
  - npm install
  - npm run build
  - cd ../server
  - ./gradlew bootJar
  - cd ..

script:
  - docker build .

# Backend tests
  - cd server
  - ./gradlew test
  - cd ..

# Frontend tests
#  - cd frontend
#  - npm run test
#  - cd ..
