version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin1
        POSTGRES_DB: docker_dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
