#!/usr/bin/env bash

#########################################
#  Omigost deployment tools             #
#########################################

#
#
# Omigost deployment tools
#
#   Bash proxy to invoke shell/python commands for deploying Omigost
#
#   Configure PYTHON_EXECUTABLE, PIP_EXECUTABLE and VIRTUALENV_EXECUTABLE
#   to set up executable names.
#
#   The manager needs at least Python 3.
#
#    Type deploy --help to get usage message.
#
#
#  Piotr Styczyński @styczynski
#  2019 MIT LICENSE
#
#

PYTHON_EXECUTABLE=python3
PIP_EXECUTABLE=pip3
VIRTUALENV_EXECUTABLE=virtualenv

DEPLOY_SCRIPT=./deploy.py
VENV_PATH=.
VENV_NAME=venv

if [ -d "./deployment" ]; then
    VENV_PATH=./deployment
    DEPLOY_SCRIPT=./deployment/deploy.py
fi

${PIP_EXECUTABLE} --version > /dev/null 2> /dev/null
result="$?"

if [ ! "$result" = "0" ]; then
    echo "[!] Could not find python 3: \"${PIP_EXECUTABLE} --version\" not work!"
    echo "[.] Trying with \"python3\"..."
    PYTHON_EXECUTABLE=python3
    ${PIP_EXECUTABLE} --version > /dev/null 2> /dev/null
    result="$?"
fi

if [ ! "$result" = "0" ]; then
    echo "[!] Could not find python 3: \"${PIP_EXECUTABLE} --version\" not work!"
    echo "[.] Trying with \"python\"..."
    PYTHON_EXECUTABLE=python
    ${PIP_EXECUTABLE} --version > /dev/null 2> /dev/null
    result="$?"
fi

if [ ! "$result" = "0" ]; then
    echo "[!] Could not find python 3: \"${PIP_EXECUTABLE} --version\" not work!"
    echo "[!] Program will terminate."
    echo "[i] Please configure ./deploy before executing"
    echo "[i] Or link python 3 executable."
    exit 1
fi


if [ ! -d "${VENV_PATH}/${VENV_NAME}" ]; then
    echo "[i] Install virtualenv by pip.."
    ${PIP_EXECUTABLE} install virtualenv

    echo "[i] Create virtual environment..."
    ${VIRTUALENV_EXECUTABLE} ${VENV_NAME}

    echo "[i] Activate environment..."
    source ${VENV_PATH}/${VENV_NAME}/Scripts/activate || source ${VENV_PATH}/${VENV_NAME}/bin/activate

    echo "[i] Install requirements..."
    ${PIP_EXECUTABLE} install -r requirements.txt

    echo "[i] Deactivate environment..."
    deactivate

    echo "[i] Virtual env set up DONE"
fi

source .${VENV_PATH}/${VENV_NAME}/Scripts/activate 2> /dev/null || source ${VENV_PATH}/${VENV_NAME}/bin/activate

${PYTHON_EXECUTABLE} ${DEPLOY_SCRIPT} --path "${VENV_PATH}" "$@"

deactivate